# -*- coding: utf-8 -*-
"""
/***************************************************************************
 shorelineChange
                                 A QGIS plugin
 This Plugin automatically extracts the shoreline given a multiband image
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-08-22
        copyright            : (C) 2023 by LocateIT 
        email                : info@locateit.co.ke
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load shorelineChange class from file shorelineChange.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .shoreline_trend import shorelineChange
    return shorelineChange(iface)
