# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'shoreline_trend_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_shorelineChangeDialogBase(object):
    def setupUi(self, shorelineChangeDialogBase):
        shorelineChangeDialogBase.setObjectName("shorelineChangeDialogBase")
        shorelineChangeDialogBase.resize(674, 377)
        self.button_box = QtWidgets.QDialogButtonBox(shorelineChangeDialogBase)
        self.button_box.setGeometry(QtCore.QRect(120, 350, 539, 25))
        self.button_box.setOrientation(QtCore.Qt.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.button_box.setObjectName("button_box")
        self.tabWidget = QtWidgets.QTabWidget(shorelineChangeDialogBase)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 661, 331))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.NDWI = QtWidgets.QTabWidget(self.tab)
        self.NDWI.setGeometry(QtCore.QRect(0, 0, 661, 301))
        self.NDWI.setObjectName("NDWI")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.inputRasterLabel = QtWidgets.QLabel(self.tab_6)
        self.inputRasterLabel.setGeometry(QtCore.QRect(20, 30, 111, 17))
        self.inputRasterLabel.setObjectName("inputRasterLabel")
        self.input = QtWidgets.QLabel(self.tab_6)
        self.input.setGeometry(QtCore.QRect(20, 100, 201, 17))
        self.input.setObjectName("input")
        self.mRasterBandComboBox_3 = QgsRasterBandComboBox(self.tab_6)
        self.mRasterBandComboBox_3.setGeometry(QtCore.QRect(240, 100, 391, 27))
        self.mRasterBandComboBox_3.setObjectName("mRasterBandComboBox_3")
        self.comboBox_2 = QtWidgets.QComboBox(self.tab_6)
        self.comboBox_2.setGeometry(QtCore.QRect(240, 30, 391, 25))
        self.comboBox_2.setObjectName("comboBox_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.tab_6)
        self.lineEdit_2.setGeometry(QtCore.QRect(240, 170, 351, 25))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.tab_6)
        self.pushButton_2.setGeometry(QtCore.QRect(600, 170, 31, 25))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_7 = QtWidgets.QLabel(self.tab_6)
        self.label_7.setGeometry(QtCore.QRect(20, 170, 121, 17))
        self.label_7.setObjectName("label_7")
        self.NDWI.addTab(self.tab_6, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.multibandRasterComboboxNDWI = QtWidgets.QComboBox(self.tab_4)
        self.multibandRasterComboboxNDWI.setGeometry(QtCore.QRect(200, 30, 421, 25))
        self.multibandRasterComboboxNDWI.setObjectName("multibandRasterComboboxNDWI")
        self.inputMultibandRasterNDWI = QtWidgets.QLabel(self.tab_4)
        self.inputMultibandRasterNDWI.setGeometry(QtCore.QRect(20, 30, 151, 17))
        self.inputMultibandRasterNDWI.setObjectName("inputMultibandRasterNDWI")
        self.browseOutputNDWI = QtWidgets.QPushButton(self.tab_4)
        self.browseOutputNDWI.setGeometry(QtCore.QRect(600, 200, 21, 25))
        self.browseOutputNDWI.setObjectName("browseOutputNDWI")
        self.outputLineEditNDWI = QtWidgets.QLineEdit(self.tab_4)
        self.outputLineEditNDWI.setGeometry(QtCore.QRect(200, 200, 391, 25))
        self.outputLineEditNDWI.setObjectName("outputLineEditNDWI")
        self.inputBandGreenLabelNDWI = QtWidgets.QLabel(self.tab_4)
        self.inputBandGreenLabelNDWI.setGeometry(QtCore.QRect(20, 90, 141, 17))
        self.inputBandGreenLabelNDWI.setObjectName("inputBandGreenLabelNDWI")
        self.greenBandComboBoxNDWI = QgsRasterBandComboBox(self.tab_4)
        self.greenBandComboBoxNDWI.setGeometry(QtCore.QRect(200, 80, 421, 27))
        self.greenBandComboBoxNDWI.setObjectName("greenBandComboBoxNDWI")
        self.nirBandComboBoxNDWI = QgsRasterBandComboBox(self.tab_4)
        self.nirBandComboBoxNDWI.setGeometry(QtCore.QRect(200, 140, 421, 27))
        self.nirBandComboBoxNDWI.setObjectName("nirBandComboBoxNDWI")
        self.inputBandNIRLabelNDWI = QtWidgets.QLabel(self.tab_4)
        self.inputBandNIRLabelNDWI.setGeometry(QtCore.QRect(20, 150, 121, 17))
        self.inputBandNIRLabelNDWI.setObjectName("inputBandNIRLabelNDWI")
        self.outputFileLabelNDWI = QtWidgets.QLabel(self.tab_4)
        self.outputFileLabelNDWI.setGeometry(QtCore.QRect(20, 210, 91, 17))
        self.outputFileLabelNDWI.setObjectName("outputFileLabelNDWI")
        self.NDWI.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.NDWI.addTab(self.tab_5, "")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tabWidget.addTab(self.tab_3, "")

        self.retranslateUi(shorelineChangeDialogBase)
        self.tabWidget.setCurrentIndex(0)
        self.NDWI.setCurrentIndex(1)
        self.button_box.rejected.connect(shorelineChangeDialogBase.reject)
        self.button_box.accepted.connect(shorelineChangeDialogBase.accept)
        QtCore.QMetaObject.connectSlotsByName(shorelineChangeDialogBase)

    def retranslateUi(self, shorelineChangeDialogBase):
        _translate = QtCore.QCoreApplication.translate
        shorelineChangeDialogBase.setWindowTitle(_translate("shorelineChangeDialogBase", "CoGEOS"))
        self.inputRasterLabel.setText(_translate("shorelineChangeDialogBase", "Input Raster "))
        self.input.setText(_translate("shorelineChangeDialogBase", "Select Band \'SWIR\' [Optional]"))
        self.pushButton_2.setText(_translate("shorelineChangeDialogBase", "..."))
        self.label_7.setText(_translate("shorelineChangeDialogBase", "Output File"))
        self.NDWI.setTabText(self.NDWI.indexOf(self.tab_6), _translate("shorelineChangeDialogBase", "Automatic Shoreline"))
        self.inputMultibandRasterNDWI.setText(_translate("shorelineChangeDialogBase", "imput Raster File"))
        self.browseOutputNDWI.setText(_translate("shorelineChangeDialogBase", "..."))
        self.inputBandGreenLabelNDWI.setText(_translate("shorelineChangeDialogBase", "Select Band \'Green\'"))
        self.inputBandNIRLabelNDWI.setText(_translate("shorelineChangeDialogBase", "Select Band \'Nir\'"))
        self.outputFileLabelNDWI.setText(_translate("shorelineChangeDialogBase", "Output File"))
        self.NDWI.setTabText(self.NDWI.indexOf(self.tab_4), _translate("shorelineChangeDialogBase", "Land-Water Mask(NDWI)"))
        self.NDWI.setTabText(self.NDWI.indexOf(self.tab_5), _translate("shorelineChangeDialogBase", "shoreline"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("shorelineChangeDialogBase", "Shoreline Extraction"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("shorelineChangeDialogBase", "Geomorphological Classiffication"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("shorelineChangeDialogBase", "About"))

from qgsrasterbandcombobox import QgsRasterBandComboBox

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    shorelineChangeDialogBase = QtWidgets.QDialog()
    ui = Ui_shorelineChangeDialogBase()
    ui.setupUi(shorelineChangeDialogBase)
    shorelineChangeDialogBase.show()
    sys.exit(app.exec_())

